name: project-costs
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  check:
    name: Check resources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    - name: Install Pulumi CLI
      uses: pulumi/action-install-pulumi-cli@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: v16.15.0
        registry-url: https://registry.npmjs.org
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2 # region doesn't matter for the cmd, just needs to be set